spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/booking_db
    username: postgres
    password: Adhi@8096

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
server:
  port: 8081
